default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: job-search-backend
  password: 619310

development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: job-search-backend
  password: 619310
  database: job_search_backend_2_development

test:
  <<: *default
  database: job_search_backend_2_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>